### ISSUE TITLE
FloatingActionButton becomes unresponsive with hasTopBarLayer: false in WoltModalSheetPage

### ISSUE THREAD

**Issue by motucraft** [woltapp/wolt_modal_sheet#105]
## Bug report

**Describe the bug**
When using WoltModalSheetPage.withCustomSliverList with hasTopBarLayer: false, the FloatingActionButton in the upper left corner becomes unresponsive to taps. Removing or commenting out hasTopBarLayer: false makes the button responsive again. This behavior suggests an issue with how the hasTopBarLayer property interacts with the button's touch events.

### Steps to reproduce

1. Run the provided Flutter application.
1. On the home screen, tap on the 'Modal Bottom Sheet' button to open the modal sheet.
1. Try to tap the FloatingActionButton in the upper left corner of the modal sheet.
1. Observe that the button is unresponsive.
1. Comment out hasTopBarLayer: false in WoltModalSheetPage.withCustomSliverList.
1. Repeat steps 1-3.
1. Observe that the button is now responsive.

### Expected behavior

The FloatingActionButton should be responsive to taps regardless of the hasTopBarLayer property's setting. The button should function correctly whether hasTopBarLayer is set to true, false, or is commented out.

---

## Additional context

<details>
<summary>pubspec.yaml</summary>

```yaml
name: wolt_modal_sheet_bug
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.4.8
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.3.2
  wolt_modal_sheet: ^0.1.4
  sliver_tools: ^0.2.12
  go_router: ^12.1.1
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.8
  build_runner: ^2.4.6
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.6

flutter:
  uses-material-design: true
```

</details>

<details>
<summary>Sample Code</summary>

```dart
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:go_router/go_router.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:sliver_tools/sliver_tools.dart';
import 'package:wolt_modal_sheet/wolt_modal_sheet.dart';

part 'main.g.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp.router(routerConfig: ref.watch(routerProvider));
  }
}

class Home extends HookWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    final pageBuilderNotifier =
        useValueNotifier<WoltModalSheetPageListBuilder>((context) => []);

    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            pageBuilderNotifier.value = (context) => [
                  WoltModalSheetPage.withCustomSliverList(
                    hasTopBarLayer: false,
                    sliverList: SliverStack(
                      insetOnOverlap: true,
                      children: [
                        SliverList(
                          delegate: SliverChildListDelegate(
                            [
                              CachedNetworkImage(
                                imageUrl:
                                    'https://consumer-static-assets.wolt.com/og_image_mall_web.jpg',
                              ),
                              const Center(
                                child: Text('Thanks for grateful package',
                                    style: TextStyle(fontSize: 24)),
                              ),
                            ],
                          ),
                        ),
                        SliverPositioned(
                          left: 16,
                          top: 16,
                          child: FloatingActionButton(
                            onPressed: () {
                              print('======= onPressed =======');
                              context.pop();
                            },
                            child: const Icon(Icons.close,
                                color: Colors.white, size: 30),
                          ),
                        ),
                      ],
                    ),
                  ),
                ];

            context.push('/bottom-sheet', extra: pageBuilderNotifier);
          },
          child: const Text('Modal Bottom Sheet'),
        ),
      ),
    );
  }
}

class SheetPage extends Page<void> {
  final ValueNotifier<WoltModalSheetPageListBuilder> pageListBuilderNotifier;
  final ValueNotifier<int>? pageIndexNotifier;

  const SheetPage({
    required this.pageListBuilderNotifier,
    this.pageIndexNotifier,
  });

  @override
  Route<void> createRoute(BuildContext context) {
    return WoltModalSheetRoute<void>(
      pageListBuilderNotifier: pageListBuilderNotifier,
      pageIndexNotifier: pageIndexNotifier,
      onModalDismissedWithBarrierTap: () => context.pop(),
      routeSettings: this,
    );
  }
}

@riverpod
GoRouter router(RouterRef ref) {
  final router = GoRouter(
    routes: [
      GoRoute(
        path: '/',
        pageBuilder: (_, __) => const MaterialPage(child: Home()),
      ),
      GoRoute(
        path: '/bottom-sheet',
        pageBuilder: (_, state) {
          final extra = state.extra!;
          if (extra is! ValueNotifier<WoltModalSheetPageListBuilder>) {
            throw UnsupportedError('Unsupported parameter. extra=$extra');
          }
          return SheetPage(pageListBuilderNotifier: extra);
        },
      ),
    ],
  );

  ref.onDispose(router.dispose);
  return router;
}
```

</details>

<img src=https://github.com/woltapp/wolt_modal_sheet/assets/35750184/c72b6496-c3f0-4208-b61d-35f22ecf781b width="30%" />

---
